### ISSUE TITLE
Update npm registry with the latest version of the package

### ISSUE THREAD

**Issue by piotrd** [fixate/angular-social-links#17]
As in the title. There is still version 0.0.1.

**Comment by piotrd** [comment]
OK, so now I'm seeing is a slight discrepancy in versioning here:

* `bower.json` and `package.json` have v.0.0.19
* bower registry shows v.0.0.21
* npm registry shows v.0.0.17

@larrybotha @sdbondi would you mind having a look at that? I'd like to use the npm version, but it's quite outdated in the registry...

**Comment by sdbondi** [comment]
Thanks for pointing that out - updated all to 0.0.22

**Comment by piotrd** [comment]
Great! Thanks for a prompt action! :)
