### ISSUE TITLE
npm module

### ISSUE THREAD

**Issue by paddotk** [fixate/angular-social-links#25]
Hi,
Can this be used with npm? The only import/declaration instruction in the readme I see is 
`angular.module('myApp', ['socialLinks']);` but I'm not sure where to place this, Angular doesn't recognise the keyword `angular` anywhere..

**Comment by larrybotha** [comment]
@paddotk this module was built for Angular 1, back in the wild west. I'd recommend looking for another module, or evaluating the source and taking from this module what works for you.

**Comment by paddotk** [comment]
@larrybotha Ah I see, thanks for the quick reply. I suggest to specify in the readme htat this is for AngularJS and not Angular, as this will probably throw more people off :)

**Comment by larrybotha** [comment]
@paddotk Is that what it's called nowadays? :P 

Done!
