### ISSUE TITLE
Fails to install through bower with Angular 1.4

### ISSUE THREAD

**Issue by deiga** [fixate/angular-social-links#5]

**Comment by sdbondi** [comment]
@deiga Could you give more details of the issue? I've tested our demo with angular v1.4.0-beta.1 which works well.

**Comment by deiga** [comment]
It fails to isntall through bower, because of unsupported angular version..

**Comment by sdbondi** [comment]
Oh well that's different. Please provide the error output from bower so I can assist. 
The angular dependency is currently ~1.x meaning any stable angular version >=1.0.0, < 2.0.0.
Note that 1.4 is currently not stable, but if your projects bower.json specifies 1.4-beta.1 explicitly as a dependency you will be able to choose your angular version. `bower install angularjs#1.4.0-beta.1 --save`

**Comment by deiga** [comment]
Apparently I was wrong, I ahve angular 1.3.10 installed, but here's the error:
```
$ bower install angular-social-links                                       
bower angular-social-links#*    cached git://github.com/fixate/angular-social-links.git#0.0.12
bower angular-social-links#*  validate 0.0.12 against git://github.com/fixate/angular-social-links.git#*
bower angular#~1.2              cached git://github.com/angular/bower-angular.git#1.2.28
bower angular#~1.2            validate 1.2.28 against git://github.com/angular/bower-angular.git#~1.2
bower angular#1.3.10            cached git://github.com/angular/bower-angular.git#1.3.10
bower angular#1.3.10          validate 1.3.10 against git://github.com/angular/bower-angular.git#1.3.10
bower                        ECONFLICT Unable to find suitable version for angular
```

**Comment by sdbondi** [comment]
This is not an issue with this repository so I'm going to close, but try adding the following resolution to your bower.json and running `bower update angular --save`. Also check that you are using the latest version of bower.

```
 "resolutions": {
    "angular": "1.3.10"
  }
```
