### ISSUE TITLE
Support for yammer share

### ISSUE THREAD

**Issue by Robert-Leggett** [fixate/angular-social-links#7]
Hi,

Can you possibly add share directive for yammer.

https://about.yammer.com/yammer-blog/introducing-yammer-share-button-3/

Thanks

**Comment by larrybotha** [comment]
@Robert-Leggett not sure that yammer has a shareable version that doesn't require an additional script tag. If you can find an example of a share link that is constituted of a single anchor, I'll be happy to take a look into adding yammer.

closing for now
